// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteHotel.Infrastructure.Data;

namespace RestauranteHotel.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RestauranteHotelContext))]
    [Migration("20210503182927_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Existencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Producto");
                });

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.ProductoCompuesto", b =>
                {
                    b.HasBaseType("RestauranteHotel.Domain.Entity.Producto");

                    b.HasDiscriminator().HasValue("ProductoCompuesto");
                });

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.ProductoSimple", b =>
                {
                    b.HasBaseType("RestauranteHotel.Domain.Entity.Producto");

                    b.Property<int?>("ProductoCompuestoId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ProductoCompuestoId");

                    b.HasDiscriminator().HasValue("ProductoSimple");
                });

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.ProductoSimple", b =>
                {
                    b.HasOne("RestauranteHotel.Domain.Entity.ProductoCompuesto", null)
                        .WithMany("Productos")
                        .HasForeignKey("ProductoCompuestoId");
                });

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.ProductoCompuesto", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
