// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteHotel.Infrastructure.Data;

namespace RestauranteHotel.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RestauranteHotelContext))]
    [Migration("20210503200815_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.Producto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Existencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.ProductoCompuesto", b =>
                {
                    b.HasBaseType("RestauranteHotel.Domain.Entity.Producto");

                    b.ToTable("ProductoCompuesto");
                });

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.ProductoSimple", b =>
                {
                    b.HasBaseType("RestauranteHotel.Domain.Entity.Producto");

                    b.Property<string>("ProductoCompuestoId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ProductoCompuestoId");

                    b.ToTable("ProductoSimple");
                });

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.ProductoCompuesto", b =>
                {
                    b.HasOne("RestauranteHotel.Domain.Entity.Producto", null)
                        .WithOne()
                        .HasForeignKey("RestauranteHotel.Domain.Entity.ProductoCompuesto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.ProductoSimple", b =>
                {
                    b.HasOne("RestauranteHotel.Domain.Entity.Producto", null)
                        .WithOne()
                        .HasForeignKey("RestauranteHotel.Domain.Entity.ProductoSimple", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteHotel.Domain.Entity.ProductoCompuesto", null)
                        .WithMany("Productos")
                        .HasForeignKey("ProductoCompuestoId");
                });

            modelBuilder.Entity("RestauranteHotel.Domain.Entity.ProductoCompuesto", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
